package com.aravind.spectra.ui

import com.aravind.spectra.model.UiState
import java.util.Locale
import kotlin.math.abs
import kotlin.math.roundToInt

fun f1(x: Double): String = String.format(Locale.US, "%.1f", x)
fun f2(x: Double): String = String.format(Locale.US, "%.2f", x)

fun fmtBytes(n: Long): String = when {
    n > 1_000_000 -> String.format(Locale.US, "%.1f MB", n / 1_000_000.0)
    n > 1_000 -> String.format(Locale.US, "%.0f KB", n / 1_000.0)
    else -> "$n B"
}

fun fmtDurationSec(sec: Double): String {
    if (!sec.isFinite()) return "—"
    val t = sec.roundToInt()
    return String.format(Locale.US, "%d:%02d", t / 60, t % 60)
}

fun fmtDurationMs(ms: Long): String = fmtDurationSec(ms / 1000.0)

fun fmtHz(hz: Double): String =
    if (hz >= 1000) String.format(Locale.US, "%.1f kHz", hz / 1000.0) else "${hz.roundToInt()} Hz"

fun fmtDb(db: Double?): String = if (db == null || !db.isFinite()) "—" else "${f1(db)} dB"

fun fmtLufs(l: Double?): String = if (l == null || !l.isFinite()) "—" else "${f1(l)} LUFS"

fun codecName(mime: String?): String = when (mime?.lowercase()) {
    "audio/flac" -> "FLAC"
    "audio/raw" -> "PCM / WAV"
    "audio/mpeg" -> "MP3"
    "audio/mp4a-latm" -> "AAC"
    "audio/vorbis" -> "Vorbis"
    "audio/opus" -> "Opus"
    "audio/alac" -> "ALAC"
    else -> mime ?: "Unknown"
}

fun buildReport(s: UiState.Success): String {
    val a = s.analysis
    val v = s.verdict
    return buildString {
        appendLine("SPECTRA REPORT")
        appendLine(s.fileName)
        s.tags.title?.let { t -> appendLine("${s.tags.artist ?: "Unknown artist"} - $t") }
        appendLine()
        appendLine("VERDICT: ${v.headline}" + (v.confidence?.let { " ($it% confidence)" } ?: ""))
        appendLine(v.summary)
        v.estimatedSource?.let { appendLine("Estimated source: $it") }
        appendLine()
        appendLine("Codec: ${codecName(s.info.codecMime)}")
        appendLine("Sample rate: ${fmtHz(a.sampleRate.toDouble())}  Channels: ${a.channelCount}")
        appendLine("Duration: ${fmtDurationSec(a.durationSec)}  Size: ${fmtBytes(s.fileSizeBytes)}")
        appendLine(
            if (a.cutoff.hasEdge) {
                "Cutoff edge: ${fmtHz(a.cutoff.cutoffHz)} of ${fmtHz(a.cutoff.nyquist)} " +
                    "(steepness ${f1(a.cutoff.strengthDb)} dB/300Hz, drop ${f1(a.cutoff.dropDb)} dB" +
                    (a.cutoff.lockRatio?.let { ", HF persistence ${(it * 100).roundToInt()}%" } ?: "") + ")"
            } else "Cutoff edge: none found"
        )
        appendLine("Integrated loudness: ${fmtLufs(a.lufs)}  LRA: ${a.lra?.let { "${f1(it)} LU" } ?: "—"}")
        appendLine("Peak: ${fmtDb(a.peakDb)}  True peak: ${fmtDb(a.truePeakDb)}  RMS: ${fmtDb(a.rmsDb)}")
        appendLine("Dynamic range: ${a.dr?.let { "DR${it.roundToInt()}" } ?: "—"}")
        appendLine("Clipping: ${a.clipRuns} runs / ${a.clipSamples} samples")
        a.stereo?.let { appendLine("Stereo correlation: ${f2(it.correlation)}") }
        appendLine()
        appendLine("FINDINGS")
        v.findings.forEach { appendLine("[${it.severity}] ${it.label}: ${it.text}") }
        appendLine()
        appendLine("Generated by Spectra")
    }
}
