package com.aravind.spectra.ui

import android.content.ContentValues
import android.content.Context
import android.graphics.Bitmap
import android.graphics.Paint
import android.graphics.Typeface
import android.os.Build
import android.os.Environment
import android.provider.MediaStore
import android.text.Layout
import android.text.StaticLayout
import android.text.TextPaint
import android.text.TextUtils
import androidx.compose.ui.geometry.CornerRadius
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.geometry.RoundRect
import androidx.compose.ui.geometry.Size
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Canvas
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.FilterQuality
import androidx.compose.ui.graphics.ImageBitmap
import androidx.compose.ui.graphics.Path
import androidx.compose.ui.graphics.PathEffect
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.asAndroidBitmap
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.graphics.drawscope.CanvasDrawScope
import androidx.compose.ui.graphics.drawscope.DrawScope
import androidx.compose.ui.graphics.drawscope.Stroke
import androidx.compose.ui.graphics.drawscope.clipPath
import androidx.compose.ui.graphics.drawscope.clipRect
import androidx.compose.ui.graphics.nativeCanvas
import androidx.compose.ui.graphics.toArgb
import androidx.compose.ui.unit.Density
import androidx.compose.ui.unit.IntOffset
import androidx.compose.ui.unit.IntSize
import androidx.compose.ui.unit.LayoutDirection
import com.aravind.spectra.dsp.AnalysisResult
import com.aravind.spectra.dsp.Verdict
import com.aravind.spectra.dsp.VerdictEngine
import com.aravind.spectra.model.UiState
import com.aravind.spectra.ui.theme.SpectraColors
import com.aravind.spectra.update.UpdateChecker
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import kotlin.math.abs
import kotlin.math.ceil
import kotlin.math.max
import kotlin.math.min
import kotlin.math.roundToInt

private const val IMG_W = 1080
private const val MARGIN = 36f
private const val GAP = 28f
private const val INNER_W = IMG_W - 2 * MARGIN - 88f
private val DIM = SpectraColors.PhosphorDim

/** One stacked section of the report: its height is known up front, drawing happens later. */
private class Block(val height: Float, val draw: DrawScope.(Float) -> Unit)

object ReportImage {

    /** Renders the full report as one tall image (1080 px wide). */
    suspend fun render(
        context: Context,
        s: UiState.Success,
        view: String,
        logScale: Boolean,
        minDb: Float
    ): Bitmap = withContext(Dispatchers.Default) {
        val a = s.analysis
        val version = UpdateChecker.currentVersion(context)
        val whenStr = SimpleDateFormat("yyyy-MM-dd HH:mm", Locale.US).format(Date())
        val cover = s.tags.coverArt?.let { decodeSampledBitmap(it, 500) }
        val spec = a.views[view] ?: a.views.getValue("all")
        val specBmp = buildSpectrogramBitmap(spec, a.sampleRate / 2.0, logScale, minDb, 0f)

        val blocks = listOf(
            headerBlock(version, whenStr),
            sourceBlock(s, cover),
            verdictBlock(s.verdict),
            spectrogramBlock(a, specBmp, logScale, minDb, viewLabel(a, view)),
            spectrumBlock(a),
            timelineBlock(a),
            levelsBlock(a),
            techBlock(s)
        )
        val footerH = 90f
        var total = MARGIN + footerH
        for (b in blocks) total += b.height + GAP

        val img = ImageBitmap(IMG_W, total.toInt())
        val canvas = Canvas(img)
        CanvasDrawScope().draw(Density(1f), LayoutDirection.Ltr, canvas, Size(IMG_W.toFloat(), total)) {
            drawBackdrop(total)
            var top = MARGIN
            for (b in blocks) {
                b.draw(this, top)
                top += b.height + GAP
            }
            ptext(
                "Generated by Spectra v$version",
                size.width / 2f, top + 34f,
                tp(24f, Color(0xFFB9A58F), mono = true, align = Paint.Align.CENTER)
            )
        }
        img.asAndroidBitmap()
    }

    /** The report split into A4-shaped pages (1080 x 1528 px). Sections stay whole where they fit. */
    suspend fun renderPages(
        context: Context,
        s: UiState.Success,
        view: String,
        logScale: Boolean,
        minDb: Float
    ): List<Bitmap> = withContext(Dispatchers.Default) {
        val a = s.analysis
        val version = UpdateChecker.currentVersion(context)
        val whenStr = SimpleDateFormat("yyyy-MM-dd HH:mm", Locale.US).format(Date())
        val cover = s.tags.coverArt?.let { decodeSampledBitmap(it, 500) }
        val spec = a.views[view] ?: a.views.getValue("all")
        val specBmp = buildSpectrogramBitmap(spec, a.sampleRate / 2.0, logScale, minDb, 0f)

        val blocks = listOf(
            headerBlock(version, whenStr),
            sourceBlock(s, cover),
            verdictBlock(s.verdict),
            spectrogramBlock(a, specBmp, logScale, minDb, viewLabel(a, view)),
            spectrumBlock(a),
            timelineBlock(a),
            levelsBlock(a),
            techBlock(s)
        )

        val pageW = IMG_W
        val pageH = IMG_W * 842f / 595f
        val cap = pageH - MARGIN - 70f

        // slice < 0: whole section at y; slice >= 0: part k of a section taller than a page
        val pages = ArrayList<ArrayList<Triple<Block, Float, Int>>>()
        var cur = ArrayList<Triple<Block, Float, Int>>()
        var y = MARGIN
        for (b in blocks) {
            if (b.height > cap) {
                if (cur.isNotEmpty()) {
                    pages += cur
                    cur = ArrayList()
                }
                val n = ceil(b.height / cap).toInt()
                for (k in 0 until n) pages += arrayListOf(Triple(b, MARGIN, k))
                y = MARGIN
            } else {
                if (y + b.height > MARGIN + cap && cur.isNotEmpty()) {
                    pages += cur
                    cur = ArrayList()
                    y = MARGIN
                }
                cur += Triple(b, y, -1)
                y += b.height + GAP
            }
        }
        if (cur.isNotEmpty()) pages += cur

        val total = pages.size
        pages.mapIndexed { idx, items ->
            val img = ImageBitmap(pageW, pageH.toInt())
            val canvas = Canvas(img)
            CanvasDrawScope().draw(Density(1f), LayoutDirection.Ltr, canvas, Size(pageW.toFloat(), pageH)) {
                drawBackdrop(pageH)
                for ((b, top, slice) in items) {
                    if (slice < 0) {
                        b.draw(this, top)
                    } else {
                        clipRect(0f, MARGIN, size.width, MARGIN + cap) {
                            b.draw(this, MARGIN - slice * cap)
                        }
                    }
                }
                ptext(
                    "Page ${idx + 1} / $total",
                    size.width / 2f, pageH - 26f,
                    tp(24f, Color(0xFFB9A58F), mono = true, align = Paint.Align.CENTER)
                )
            }
            img.asAndroidBitmap()
        }
    }

    /** Saves the image to Pictures/Spectra (visible in the gallery). Returns where it went. */
    suspend fun saveToGallery(context: Context, bitmap: Bitmap, baseName: String): String =
        withContext(Dispatchers.IO) {
            val stamp = SimpleDateFormat("yyyyMMdd-HHmmss", Locale.US).format(Date())
            val name = "Spectra-${safe(baseName)}-$stamp.png"
            if (Build.VERSION.SDK_INT >= 29) {
                val values = ContentValues().apply {
                    put(MediaStore.Images.Media.DISPLAY_NAME, name)
                    put(MediaStore.Images.Media.MIME_TYPE, "image/png")
                    put(MediaStore.Images.Media.RELATIVE_PATH, "Pictures/Spectra")
                    put(MediaStore.Images.Media.IS_PENDING, 1)
                }
                val resolver = context.contentResolver
                val uri = resolver.insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI, values)
                    ?: error("Could not create the image file")
                val out = resolver.openOutputStream(uri) ?: error("Could not open the image file")
                out.use { bitmap.compress(Bitmap.CompressFormat.PNG, 100, it) }
                values.clear()
                values.put(MediaStore.Images.Media.IS_PENDING, 0)
                resolver.update(uri, values, null, null)
                "Pictures/Spectra"
            } else {
                val dir = context.getExternalFilesDir(Environment.DIRECTORY_PICTURES) ?: context.filesDir
                val f = File(dir, name)
                f.outputStream().use { bitmap.compress(Bitmap.CompressFormat.PNG, 100, it) }
                f.absolutePath
            }
        }
}

private fun safe(s: String): String =
    s.replace(Regex("[^A-Za-z0-9._-]+"), "_").trim('_').take(40).ifEmpty { "report" }

private fun viewLabel(a: AnalysisResult, view: String): String = when (view) {
    "ch1" -> "L"
    "ch2" -> "R"
    "mid" -> "MID"
    "side" -> "SIDE"
    else -> if (a.channelCount == 1) "MONO" else "L+R"
}

private fun hzShort(f: Double): String {
    if (f < 1000) return f.roundToInt().toString()
    val k = f / 1000.0
    return if (abs(k - k.roundToInt()) < 0.05) "${k.roundToInt()}k" else String.format(Locale.US, "%.1fk", k)
}

// ---------------------------------------------------------------- text helpers

private fun tp(
    size: Float,
    color: Color,
    bold: Boolean = false,
    mono: Boolean = false,
    align: Paint.Align = Paint.Align.LEFT,
    spacing: Float = 0f,
    glow: Boolean = false
): TextPaint = TextPaint(Paint.ANTI_ALIAS_FLAG).apply {
    textSize = size
    this.color = color.toArgb()
    textAlign = align
    letterSpacing = spacing
    typeface = Typeface.create(
        if (mono) Typeface.MONOSPACE else Typeface.DEFAULT,
        if (bold) Typeface.BOLD else Typeface.NORMAL
    )
    if (glow) setShadowLayer(size * 0.35f, 0f, 0f, color.copy(alpha = 0.7f).toArgb())
}

private fun layout(text: String, paint: TextPaint, width: Float, maxLines: Int = Int.MAX_VALUE): StaticLayout =
    StaticLayout.Builder.obtain(text, 0, text.length, paint, width.toInt().coerceAtLeast(1))
        .setAlignment(Layout.Alignment.ALIGN_NORMAL)
        .setLineSpacing(0f, 1.12f)
        .setMaxLines(maxLines)
        .setEllipsize(TextUtils.TruncateAt.END)
        .build()

private fun DrawScope.ptext(t: String, x: Float, y: Float, p: Paint) {
    drawContext.canvas.nativeCanvas.drawText(t, x, y, p)
}

private fun DrawScope.drawLayout(l: StaticLayout, x: Float, y: Float) {
    val c = drawContext.canvas.nativeCanvas
    c.save()
    c.translate(x, y)
    l.draw(c)
    c.restore()
}

private fun DrawScope.engraved(t: String, x: Float, y: Float, size: Float) {
    ptext(t, x, y + 2f, tp(size, Color.White.copy(alpha = 0.95f), bold = true, spacing = 0.12f))
    ptext(t, x, y, tp(size, SpectraColors.InkSoft, bold = true, spacing = 0.12f))
}

// ---------------------------------------------------------------- hardware look

private fun roundPath(x: Float, y: Float, w: Float, h: Float, r: Float): Path =
    Path().apply { addRoundRect(RoundRect(x, y, x + w, y + h, r, r)) }

private fun DrawScope.drawBackdrop(totalH: Float) {
    drawRect(Brush.verticalGradient(listOf(SpectraColors.WoodTop, SpectraColors.WoodBottom), startY = 0f, endY = totalH))
    var y = 0f
    var i = 0
    while (y < totalH) {
        val a = 0.015f + ((i * 7919) % 11) / 11f * 0.05f
        drawLine(Color(0xFF8A5E3C).copy(alpha = a), Offset(0f, y), Offset(size.width, y), 3f)
        y += 10f
        i++
    }
    drawRect(
        Brush.radialGradient(
            listOf(Color.Transparent, Color(0xAA000000)),
            center = Offset(size.width / 2f, totalH * 0.4f),
            radius = max(size.width, totalH) * 0.8f
        )
    )
}

private fun DrawScope.screw(c: Offset, r: Float, angle: Float) {
    drawCircle(Color.Black.copy(alpha = 0.35f), r + 2f, c + Offset(0f, 2f))
    drawCircle(
        Brush.radialGradient(
            listOf(Color(0xFFFAFAFA), Color(0xFF9FA3AB), Color(0xFF4F535B)),
            center = c - Offset(r * 0.3f, r * 0.3f),
            radius = r * 1.5f
        ),
        r,
        c
    )
    drawCircle(Color(0xFF3C3F46), r, c, style = Stroke(2f))
    val t = Math.toRadians(angle.toDouble())
    val d = Offset((kotlin.math.cos(t) * r * 0.7).toFloat(), (kotlin.math.sin(t) * r * 0.7).toFloat())
    drawLine(Color(0xFF2B2E34), c - d, c + d, 3f, StrokeCap.Round)
}

private fun DrawScope.plate(left: Float, top: Float, w: Float, h: Float) {
    val r = 40f
    for (i in 1..4) {
        drawRoundRect(
            Color.Black.copy(alpha = 0.10f),
            Offset(left - i, top + 4f + i * 3f),
            Size(w + 2f * i, h),
            CornerRadius(r + i)
        )
    }
    drawRoundRect(
        Brush.verticalGradient(
            listOf(SpectraColors.MetalHi, SpectraColors.MetalMid, SpectraColors.MetalLo),
            startY = top, endY = top + h
        ),
        Offset(left, top), Size(w, h), CornerRadius(r)
    )
    clipPath(roundPath(left, top, w, h, r)) {
        var y = top + 6f
        var i = 0
        while (y < top + h) {
            drawLine(
                if (i % 2 == 0) Color.White.copy(alpha = 0.10f) else Color.Black.copy(alpha = 0.035f),
                Offset(left, y), Offset(left + w, y), 2f
            )
            y += 6f
            i++
        }
    }
    drawRoundRect(
        Brush.verticalGradient(
            listOf(Color.White.copy(alpha = 0.9f), Color.Transparent, Color.Black.copy(alpha = 0.35f)),
            startY = top, endY = top + h
        ),
        Offset(left, top), Size(w, h), CornerRadius(r), style = Stroke(4f)
    )
    screw(Offset(left + 28f, top + 28f), 10f, 35f)
    screw(Offset(left + w - 28f, top + 28f), 10f, 110f)
    screw(Offset(left + 28f, top + h - 28f), 10f, 75f)
    screw(Offset(left + w - 28f, top + h - 28f), 10f, 160f)
}

private fun DrawScope.glass(x: Float, y: Float, w: Float, h: Float) {
    drawRoundRect(
        Brush.verticalGradient(listOf(SpectraColors.MetalEdgeDark, Color(0xFFC3C7CF)), startY = y, endY = y + h),
        Offset(x, y), Size(w, h), CornerRadius(28f)
    )
    val ix = x + 7f
    val iy = y + 7f
    val iw = w - 14f
    val ih = h - 14f
    drawRoundRect(
        Brush.verticalGradient(listOf(SpectraColors.ScreenTop, SpectraColors.ScreenBottom), startY = iy, endY = iy + ih),
        Offset(ix, iy), Size(iw, ih), CornerRadius(22f)
    )
    clipPath(roundPath(ix, iy, iw, ih, 22f)) {
        drawRect(
            Brush.verticalGradient(listOf(Color.Black.copy(alpha = 0.6f), Color.Transparent), startY = iy, endY = iy + 36f),
            Offset(ix, iy), Size(iw, 36f)
        )
        drawRect(
            Brush.linearGradient(
                listOf(Color.White.copy(alpha = 0.09f), Color.Transparent),
                start = Offset(x, y), end = Offset(x + w * 0.7f, y + h * 0.55f)
            ),
            Offset(ix, iy), Size(iw, ih)
        )
    }
}

private fun DrawScope.led(c: Offset, r: Float, color: Color, on: Boolean = true) {
    if (on) {
        drawCircle(
            Brush.radialGradient(listOf(color.copy(alpha = 0.55f), Color.Transparent), center = c, radius = r * 2.8f),
            r * 2.8f, c
        )
    }
    val body = if (on) listOf(Color.White.copy(alpha = 0.95f), color, color.shade(0.55f))
    else listOf(Color(0xFF6C717A), Color(0xFF30343B), Color(0xFF16181C))
    drawCircle(Brush.radialGradient(body, center = c - Offset(r * 0.3f, r * 0.35f), radius = r * 1.3f), r, c)
    drawCircle(Color.Black.copy(alpha = 0.55f), r, c, style = Stroke(2f))
}

private fun DrawScope.ladder(x: Float, y: Float, w: Float, h: Float, frac: Float, segments: Int = 40, tint: Color? = null) {
    val gap = 4f
    val segW = (w - gap * (segments - 1)) / segments
    val lit = (frac.coerceIn(0f, 1f) * segments).roundToInt()
    for (i in 0 until segments) {
        val z = i.toFloat() / segments
        val base = tint ?: when {
            z < 0.62f -> SpectraColors.Green
            z < 0.85f -> SpectraColors.Amber
            else -> SpectraColors.Red
        }
        val sx = x + i * (segW + gap)
        val on = i < lit
        drawRoundRect(if (on) base else base.shade(0.2f), Offset(sx, y), Size(segW, h), CornerRadius(4f))
        if (on) drawRoundRect(Color.White.copy(alpha = 0.35f), Offset(sx, y), Size(segW, h * 0.4f), CornerRadius(4f))
    }
}

/** A metal section with engraved title and lamp; [content] gets the inner x, y and width. */
private fun panel(
    title: String,
    lamp: Color?,
    contentHeight: Float,
    content: DrawScope.(Float, Float, Float) -> Unit
): Block {
    val headerH = 96f
    val h = headerH + contentHeight + 40f
    return Block(h) { top ->
        val left = MARGIN
        val w = size.width - 2f * MARGIN
        plate(left, top, w, h)
        engraved(title.uppercase(), left + 60f, top + 64f, 30f)
        if (lamp != null) led(Offset(left + w - 66f, top + 52f), 15f, lamp)
        content(left + 44f, top + headerH, w - 88f)
    }
}

// ---------------------------------------------------------------- sections

private fun headerBlock(version: String, whenStr: String): Block =
    panel("Spectra SA-1", SpectraColors.Green, 190f) { x, y, w ->
        engraved("SPECTRA", x, y + 108f, 120f)
        engraved("AUDIO FORENSICS REPORT", x + 4f, y + 160f, 28f)
        ptext(whenStr, x + w, y + 60f, tp(26f, SpectraColors.InkSoft, mono = true, align = Paint.Align.RIGHT))
        ptext("v$version", x + w, y + 98f, tp(26f, SpectraColors.InkSoft, mono = true, align = Paint.Align.RIGHT))
    }

private fun sourceBlock(s: UiState.Success, cover: Bitmap?): Block {
    val a = s.analysis
    val pad = 26f
    val art = if (cover != null) 250f else 0f
    val textX = pad + (if (art > 0f) art + 26f else 0f)
    val textW = INNER_W - textX - pad
    val lossless = VerdictEngine.isLossless(s.info.codecMime)
    val depth = if (!lossless) "" else when {
        s.info.declaredBits != null -> " · ${s.info.declaredBits}-bit"
        a.effectiveBits != null -> " · ${a.effectiveBits}-bit eff."
        else -> ""
    }

    val l = ArrayList<StaticLayout>()
    l += layout(s.tags.title ?: s.fileName, tp(40f, SpectraColors.Phosphor, bold = true, mono = true, glow = true), textW, 3)
    s.tags.artist?.let { l += layout(it, tp(34f, SpectraColors.Amber, mono = true, glow = true), textW, 1) }
    s.tags.album?.let { l += layout(it, tp(30f, DIM, mono = true), textW, 1) }
    l += layout(
        "${codecName(s.info.codecMime)}$depth · ${fmtHz(a.sampleRate.toDouble())} · ${a.channelCount} ch",
        tp(28f, DIM, mono = true), textW, 2
    )
    val extras = listOfNotNull(s.tags.year, s.tags.genre).joinToString(" · ")
    l += layout(
        "${fmtDurationSec(a.durationSec)} · ${fmtBytes(s.fileSizeBytes)}" + (if (extras.isNotEmpty()) " · $extras" else ""),
        tp(28f, DIM, mono = true), textW, 2
    )
    var stackH = 10f * (l.size - 1)
    for (lay in l) stackH += lay.height
    val gh = 2f * pad + max(art, stackH)

    return panel("Source", SpectraColors.Green, gh) { x, y, w ->
        glass(x, y, w, gh)
        if (cover != null) {
            val side = min(cover.width, cover.height)
            val ax = x + pad
            val ay = y + pad
            clipPath(roundPath(ax, ay, art, art, 18f)) {
                drawImage(
                    cover.asImageBitmap(),
                    IntOffset((cover.width - side) / 2, (cover.height - side) / 2),
                    IntSize(side, side),
                    IntOffset(ax.toInt(), ay.toInt()),
                    IntSize(art.toInt(), art.toInt())
                )
            }
            drawRoundRect(Color.Black.copy(alpha = 0.5f), Offset(ax, ay), Size(art, art), CornerRadius(18f), style = Stroke(3f))
        }
        var ty = y + pad
        for (lay in l) {
            drawLayout(lay, x + textX, ty)
            ty += lay.height + 10f
        }
    }
}

private fun verdictBlock(v: Verdict): Block {
    val tone = sevColor(v.severity)
    val pad = 28f
    val summary = layout(v.summary, tp(29f, SpectraColors.Phosphor.copy(alpha = 0.9f), mono = true), INNER_W - 2f * pad)
    val ev = v.confidence
    val src = v.estimatedSource
    val gh = pad + 74f + summary.height + 14f + (if (ev != null) 78f else 0f) + (if (src != null) 50f else 0f) + pad

    val fl = v.findings.map { it to layout(it.text, tp(29f, SpectraColors.Ink), INNER_W - 44f) }
    var fh = 0f
    for (p in fl) fh += 34f + p.second.height + 22f

    return panel("Authenticity", tone, gh + 26f + fh) { x, y, w ->
        glass(x, y, w, gh)
        led(Offset(x + pad + 24f, y + pad + 32f), 22f, tone)
        ptext(v.headline.uppercase(), x + pad + 70f, y + pad + 48f, tp(50f, tone, bold = true, mono = true, glow = true))
        var ty = y + pad + 74f
        drawLayout(summary, x + pad, ty)
        ty += summary.height + 14f
        if (ev != null) {
            ptext("EVIDENCE $ev%", x + pad, ty + 26f, tp(26f, tone, mono = true))
            ladder(x + pad, ty + 40f, w - 2f * pad, 26f, ev / 100f, 30, tone)
            ty += 78f
        }
        if (src != null) ptext("SOURCE: $src", x + pad, ty + 30f, tp(28f, SpectraColors.Amber, mono = true))

        var fy = y + gh + 26f
        for ((f, lay) in fl) {
            led(Offset(x + 14f, fy + 16f), 11f, sevColor(f.severity))
            engraved(f.label.uppercase(), x + 44f, fy + 26f, 24f)
            drawLayout(lay, x + 44f, fy + 34f)
            fy += 34f + lay.height + 22f
        }
    }
}

private fun spectrogramBlock(a: AnalysisResult, bmp: ImageBitmap, logScale: Boolean, minDb: Float, label: String): Block {
    val bh = 480f
    val gh = 20f + bh + 14f + 34f + 14f + 16f + 38f + 20f
    return panel("Spectrogram · $label", SpectraColors.Phosphor, gh) { x, y, w ->
        glass(x, y, w, gh)
        val bx = x + 20f + 92f
        val by = y + 20f
        val bw = w - 20f - 92f - 20f
        drawImage(
            bmp,
            IntOffset.Zero, IntSize(bmp.width, bmp.height),
            IntOffset(bx.toInt(), by.toInt()), IntSize(bw.toInt(), bh.toInt()),
            filterQuality = FilterQuality.Low
        )

        val nyq = a.sampleRate / 2.0
        val yp = tp(22f, DIM, mono = true, align = Paint.Align.RIGHT)
        val marks = if (logScale) listOf(20.0, 100.0, 1000.0, 10000.0, nyq)
        else listOf(0.0, 0.25, 0.5, 0.75, 1.0).map { it * nyq }
        for (f in marks) {
            if (f > nyq + 1) continue
            val fy = (by + bh * (1.0 - freqToFrac(f, nyq, logScale)).toFloat()).coerceIn(by + 18f, by + bh - 4f)
            ptext(hzShort(f), bx - 12f, fy + 8f, yp)
        }
        for (i in 0..4) {
            val al = when (i) {
                0 -> Paint.Align.LEFT
                4 -> Paint.Align.RIGHT
                else -> Paint.Align.CENTER
            }
            ptext(fmtDurationSec(a.durationSec * i / 4.0), bx + bw * i / 4f, by + bh + 36f, tp(22f, DIM, mono = true, align = al))
        }
        val ly = by + bh + 62f
        drawRect(
            Brush.horizontalGradient(*SpectrogramPalette.legendStops, startX = bx, endX = bx + bw),
            Offset(bx, ly), Size(bw, 16f)
        )
        ptext("${minDb.roundToInt()} dB", bx, ly + 42f, tp(22f, DIM, mono = true))
        ptext("0 dB", bx + bw, ly + 42f, tp(22f, DIM, mono = true, align = Paint.Align.RIGHT))
    }
}

private fun spectrumBlock(a: AnalysisResult): Block {
    val gh = 360f
    return panel("Average spectrum", SpectraColors.Phosphor, gh) { x, y, w ->
        glass(x, y, w, gh)
        val avg = a.avgSpectrumDb
        val nyq = a.sampleRate / 2.0
        val left = x + 96f
        val top = y + 24f
        val pw = w - 96f - 28f
        val ph = gh - 24f - 56f

        var mx = -200f
        for (v in avg) if (v > mx) mx = v
        val hi = ceil(mx / 10f) * 10f
        val lo = hi - 110f
        fun yOf(db: Float): Float = top + ph * (1f - ((db - lo) / (hi - lo)).coerceIn(0f, 1f))
        fun xOf(i: Int): Float = left + pw * i / (avg.size - 1).toFloat()

        val grid = SpectraColors.Phosphor.copy(alpha = 0.13f)
        val rp = tp(22f, DIM, mono = true, align = Paint.Align.RIGHT)
        var g = hi
        while (g >= lo) {
            val gy = yOf(g)
            drawLine(grid, Offset(left, gy), Offset(left + pw, gy), 2f)
            ptext(g.roundToInt().toString(), left - 12f, gy + 8f, rp)
            g -= 20f
        }
        val cp = tp(22f, DIM, mono = true, align = Paint.Align.CENTER)
        var fk = 0.0
        while (fk <= nyq) {
            val gx = left + pw * (fk / nyq).toFloat()
            drawLine(grid, Offset(gx, top), Offset(gx, top + ph), 2f)
            ptext(hzShort(fk), gx, top + ph + 34f, cp)
            fk += 4000.0
        }

        val line = Path()
        val fill = Path()
        for (i in avg.indices) {
            val px = xOf(i)
            val py = yOf(avg[i])
            if (i == 0) {
                line.moveTo(px, py)
                fill.moveTo(px, top + ph)
                fill.lineTo(px, py)
            } else {
                line.lineTo(px, py)
                fill.lineTo(px, py)
            }
        }
        fill.lineTo(xOf(avg.size - 1), top + ph)
        fill.close()
        drawPath(fill, Brush.verticalGradient(listOf(SpectraColors.Phosphor.copy(alpha = 0.35f), Color.Transparent), startY = top, endY = top + ph))
        drawPath(line, SpectraColors.Phosphor, style = Stroke(3f, join = StrokeJoin.Round))

        if (a.cutoff.hasEdge) {
            val cx = left + pw * (a.cutoff.cutoffHz / nyq).toFloat()
            drawLine(
                SpectraColors.Amber, Offset(cx, top), Offset(cx, top + ph), 3f,
                pathEffect = PathEffect.dashPathEffect(floatArrayOf(18f, 14f))
            )
            val right = cx > left + pw * 0.7f
            ptext(
                "CUT " + fmtHz(a.cutoff.cutoffHz),
                if (right) cx - 10f else cx + 10f, top + 26f,
                tp(22f, SpectraColors.Amber, mono = true, align = if (right) Paint.Align.RIGHT else Paint.Align.LEFT)
            )
        }
    }
}

private fun timelineBlock(a: AnalysisResult): Block {
    val gh = 400f
    return panel("Loudness over time", SpectraColors.Phosphor, gh) { x, y, w ->
        glass(x, y, w, gh)
        val series = a.loudnessSeries
        val dur = a.durationSec
        if (series.size < 2) {
            ptext("Needs at least 4 seconds of audio", x + 30f, y + 70f, tp(26f, DIM, mono = true))
        } else {
            val left = x + 96f
            val top = y + 26f
            val pw = w - 96f - 28f
            val ph = 240f
            val stripH = 36f

            var mn = Float.MAX_VALUE
            var mx = -Float.MAX_VALUE
            for (v in series) {
                if (!v.isNaN()) {
                    if (v < mn) mn = v
                    if (v > mx) mx = v
                }
            }
            if (mn > mx) {
                mn = -30f
                mx = -10f
            }
            val lo = kotlin.math.floor((mn - 2f) / 6f) * 6f
            var hi = ceil((mx + 2f) / 6f) * 6f
            if (hi - lo < 12f) hi = lo + 12f
            val hiF = hi
            fun yOf(db: Float): Float = top + ph * (1f - ((db - lo) / (hiF - lo)).coerceIn(0f, 1f))
            fun xOf(t: Double): Float = left + pw * (t / dur).toFloat().coerceIn(0f, 1f)

            val grid = SpectraColors.Phosphor.copy(alpha = 0.13f)
            val rp = tp(22f, DIM, mono = true, align = Paint.Align.RIGHT)
            var g = lo
            while (g <= hiF + 0.01f) {
                val gy = yOf(g)
                drawLine(grid, Offset(left, gy), Offset(left + pw, gy), 2f)
                ptext(g.roundToInt().toString(), left - 12f, gy + 8f, rp)
                g += 6f
            }

            val line = Path()
            var pen = false
            for (i in series.indices) {
                val v = series[i]
                if (v.isNaN()) {
                    pen = false
                    continue
                }
                val px = xOf(i + 1.5)
                val py = yOf(v)
                if (!pen) {
                    line.moveTo(px, py)
                    pen = true
                } else {
                    line.lineTo(px, py)
                }
            }
            drawPath(line, SpectraColors.Phosphor, style = Stroke(3f, join = StrokeJoin.Round))

            a.lufs?.let { l ->
                val iy = yOf(l.toFloat())
                drawLine(
                    SpectraColors.Amber, Offset(left, iy), Offset(left + pw, iy), 3f,
                    pathEffect = PathEffect.dashPathEffect(floatArrayOf(18f, 14f))
                )
                ptext("I ${f1(l)}", left + 8f, iy - 8f, tp(22f, SpectraColors.Amber, mono = true))
            }

            val stripTop = top + ph + 14f
            for (sec in a.clipSeconds.indices) {
                val c = a.clipSeconds[sec]
                if (c <= 0) continue
                val frac = (kotlin.math.log10(1.0 + c) / 4.0).toFloat().coerceIn(0.2f, 1f)
                val bx = xOf(sec + 0.5)
                drawLine(
                    SpectraColors.Red,
                    Offset(bx, stripTop + stripH),
                    Offset(bx, stripTop + stripH * (1f - frac)),
                    4f
                )
            }
            ptext("clip", left - 12f, stripTop + stripH, tp(20f, SpectraColors.Red, mono = true, align = Paint.Align.RIGHT))

            for (i in 0..4) {
                val al = when (i) {
                    0 -> Paint.Align.LEFT
                    4 -> Paint.Align.RIGHT
                    else -> Paint.Align.CENTER
                }
                ptext(fmtDurationSec(dur * i / 4.0), left + pw * i / 4f, stripTop + stripH + 34f, tp(22f, DIM, mono = true, align = al))
            }
        }
    }
}

private fun gridHeight(n: Int): Float = ceil(n / 2f) * 100f + 36f

private fun DrawScope.drawGrid(x: Float, y: Float, w: Float, items: List<Readout>) {
    glass(x, y, w, gridHeight(items.size))
    items.forEachIndexed { i, r ->
        val cx = x + 34f + (i % 2) * (w / 2f)
        val ry = y + 26f + (i / 2) * 100f
        ptext(r.label.uppercase(), cx, ry + 24f, tp(22f, DIM, mono = true, spacing = 0.08f))
        ptext(r.value, cx, ry + 68f, tp(38f, r.tone, mono = true, glow = true))
    }
}

private fun levelItems(a: AnalysisResult): List<Readout> {
    val over = a.truePeakDb > 0.0
    val dr = a.dr
    val items = ArrayList<Readout>()
    items += Readout("Integrated", fmtLufs(a.lufs))
    items += Readout("Loud. range", a.lra?.let { "${f1(it)} LU" } ?: "—")
    items += Readout("Max momentary", fmtLufs(a.maxMomentary))
    items += Readout(
        "Dynamic range",
        dr?.let { "DR${it.roundToInt()}" } ?: "—",
        if (dr != null && dr <= 7.0) SpectraColors.Amber else SpectraColors.Phosphor
    )
    items += Readout("Sample peak", fmtDb(a.peakDb))
    items += Readout("True peak", fmtDb(a.truePeakDb), if (over) SpectraColors.Red else SpectraColors.Phosphor)
    items += Readout("RMS", fmtDb(a.rmsDb))
    items += Readout(
        "Clipping",
        when {
            a.clipRuns > 0 -> "${a.clipRuns} runs"
            a.clipSamples > 0 -> "${a.clipSamples} touches"
            else -> "none"
        },
        if (a.clipRuns > 0) SpectraColors.Amber else SpectraColors.Phosphor
    )
    a.stereo?.let { st ->
        items += Readout("Correlation", f2(st.correlation), if (st.correlation < 0.0) SpectraColors.Amber else SpectraColors.Phosphor)
        items += Readout("Side vs mid", if (st.dualMono) "mono" else "${f1(st.sideDb - st.midDb)} dB")
        items += Readout("Balance L/R", "${f1(st.balanceDb)} dB")
    }
    return items
}

private fun levelsBlock(a: AnalysisResult): Block {
    val items = levelItems(a)
    val ladH = a.channels.size * 96f + 28f
    val gridH = gridHeight(items.size)
    val lamp = if (a.truePeakDb > 0.0) SpectraColors.Red else SpectraColors.Green
    return panel("Loudness & levels", lamp, ladH + 24f + gridH) { x, y, w ->
        glass(x, y, w, ladH)
        a.channels.forEachIndexed { i, ch ->
            val ry = y + 22f + i * 96f
            val name = if (a.channelCount == 2) (if (i == 0) "L" else "R") else "CH${i + 1}"
            val tone = if (ch.truePeakDb > 0.0) SpectraColors.Red else SpectraColors.Phosphor
            ptext("$name  PK ${f1(ch.peakDb)}  TP ${f1(ch.truePeakDb)}", x + 28f, ry + 26f, tp(24f, tone, mono = true))
            ladder(x + 28f, ry + 40f, w - 56f, 30f, ((ch.peakDb + 60.0) / 60.0).toFloat())
        }
        drawGrid(x, y + ladH + 24f, w, items)
    }
}

private fun techItems(s: UiState.Success): List<Readout> {
    val a = s.analysis
    val lossless = VerdictEngine.isLossless(s.info.codecMime)
    val items = ArrayList<Readout>()
    items += Readout("Codec", codecName(s.info.codecMime))
    items += Readout("Sample rate", fmtHz(a.sampleRate.toDouble()))
    items += Readout("Channels", a.channelCount.toString())
    items += Readout("Decoder", s.info.engine)
    s.info.facts?.bitrateKbps?.let { items += Readout("Bitrate", "$it kbps") }
    s.info.facts?.encoder?.let { items += Readout("Encoder", it.take(18)) }
    items += Readout("Decoded as", s.info.encoding)
    items += Readout(
        "Bit depth",
        if (!lossless) "n/a (lossy)" else when {
            s.info.declaredBits != null && a.effectiveBits != null -> "${s.info.declaredBits} (eff. ${a.effectiveBits})"
            a.effectiveBits != null -> "${a.effectiveBits}-bit eff."
            else -> "16-bit (decoder)"
        }
    )
    items += Readout("Duration", fmtDurationSec(a.durationSec))
    items += Readout("Nyquist", fmtHz(a.sampleRate / 2.0))
    items += Readout("Cutoff edge", if (a.cutoff.hasEdge) fmtHz(a.cutoff.cutoffHz) else "none found")
    if (a.cutoff.hasEdge) {
        items += Readout("Edge steepness", "${f1(a.cutoff.strengthDb)} dB/300Hz")
        a.cutoff.lockRatio?.let { items += Readout("HF persistence", "${(it * 100).roundToInt()} %") }
    }
    items += Readout("File size", fmtBytes(s.fileSizeBytes))
    items += Readout("Frames", a.totalFrames.toString())
    items += Readout("DC offset", f2(a.channels.maxOf { abs(it.dcOffset) } * 100) + " %")
    s.tags.bitrateBps?.let { items += Readout("Tag bitrate", "${it / 1000} kbps") }
    items += Readout("Analysis time", String.format(Locale.US, "%.1f s", s.tookMs / 1000.0))
    return items
}

private fun techBlock(s: UiState.Success): Block {
    val items = techItems(s)
    return panel("Technical data", null, gridHeight(items.size)) { x, y, w ->
        drawGrid(x, y, w, items)
    }
}
